### ISSUE TITLE
fine-tuning and evaluation

### ISSUE THREAD

**Issue by CaipingPeng** [MAGIC-AI4Med/MMedLM#3]
Hi, I am a researcher in medical large model. I am excited to see your work.
Now, I want you futher develop your model , but I have not saw the evalute metrics file, could you provide that? It will be helpful ,thank you!

**Comment by Henrychur** [comment]
Thank you for your attention to our work. We have updated the Metric code for reference here: 
https://github.com/MAGIC-AI4Med/MMedLM/tree/main/metrics

If you have any further question, feel free to contact me.

**Comment by CaipingPeng** [comment]
> Thank you for your attention to our work. We have updated the Metric code for reference here: https://github.com/MAGIC-AI4Med/MMedLM/tree/main/metrics
> 
> If you have any further question, feel free to contact me.

thank you!
