### ISSUE TITLE
How and where to submit evaluations?

### ISSUE THREAD

**Issue by zhimin-z** [MAGIC-AI4Med/MMedLM#4]
![image](https://github.com/user-attachments/assets/ca0c91f8-d352-4de8-b600-ae6ebb6bb04e)
Unfortunately, I cannot find any related information in the GitHub repo.
<img width="619" alt="image" src="https://github.com/user-attachments/assets/d18e36b9-c2b7-4117-a1cc-281ec6af2ec8">

**Comment by Henrychur** [comment]
Thank you for your reminder. I've now added a [tutorial](https://github.com/MAGIC-AI4Med/MMedLM/blob/main/SubmissionTutorial.md) related to submissions in the repo. If you have any further questions, please feel free to reach out at any time.

**Comment by zhimin-z** [comment]
Found it, closed!
