### ISSUE TITLE
Missing profile

### ISSUE THREAD

**Issue by bigdataLyt** [MAGIC-AI4Med/MMedLM#5]
Imeeting this problem: ValueError: Can't find 'adapter_config.json' at 'Henrychur/MMed-Llama-3-8B-EnIns'

**Comment by Henrychur** [comment]
Hi,

This model is a fully fine-tuned version, meaning it does not use Parameter-Efficient Fine-Tuning (PEFT) methods such as LoRA. You can load it directly with the following code:

```python
model = AutoModelForCausalLM.from_pretrained("Henrychur/MMed-Llama-3-8B-EnIns")
```

**Comment by bigdataLyt** [comment]
thanks for your recover, it is really expediency
