### ISSUE TITLE
prepare_data() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by JV-X** [MAGIC-AI4Med/MMedLM#6]
Hello, I downloaded the code and downloaded ```MMedLM2-1_8B``` on huggingface, and ran the code, but when I executed ```bash inference.sh```, I got the following error.Is there something wrong?

error log:
```
(mmedlm) hygx@hygx:~/code/MMedLM/inference$ bash inference.sh
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.18s/it]
Traceback (most recent call last):
  File "inference.py", line 150, in <module>
    validate()
  File "inference.py", line 146, in validate
    inference(filepath, model, tokenizer, args.save_dir, args.is_with_rationale)
  File "inference.py", line 110, in inference
    data_list = prepare_data(data_list, model, tokenizer)
TypeError: prepare_data() takes 1 positional argument but 3 were given
```

**Comment by Henrychur** [comment]
Hello, thank you for reaching out and providing the error details!

It seems like the error is happening because of an incorrect call to the `prepare_data()` function in the `inference.py` script. We have fix the bug now.

**Comment by JV-X** [comment]
> Hello, thank you for reaching out and providing the error details!
> 
> It seems like the error is happening because of an incorrect call to the `prepare_data()` function in the `inference.py` script. We have fix the bug now.

I read the code and found that only the ```model``` and ```tokenizer``` variables were deleted. However, these two variables are not used after being deleted. Can the results be predicted normally in this way?

**Comment by Henrychur** [comment]
In `prepare_data`, we prepare the data with our prompt.
```py
def prepare_data(data_list: Sequence[dict]) -> Sequence[dict]:
    prompt_input, prompt_no_input = PROMPT_DICT["prompt_input"], PROMPT_DICT["prompt_no_input"]
    for _idx in tqdm(range(len(data_list))):
        data_entry = data_list[_idx]
        data_list[_idx]['sample_id'] = _idx

        data_list[_idx]['pmc_input'] = prompt_input.format_map(data_entry) if data_entry.get("input", "") != "" else prompt_no_input.format_map(data_entry)
        data_list[_idx]['pmc_output'] = data_entry['output']
        data_list[_idx]['rationale'] = data_entry['rationale']
    return data_list
```

and in `inference_on_one`, we first tokenize the string, and use `model.generate()` to generate the output.
```py
def inference_on_one(input_str: Sequence[str], model, tokenizer) -> str:
    model_inputs = tokenizer(
      input_str,
      return_tensors='pt',
      padding=True,
    )

    topk_output = model.generate(
        model_inputs.input_ids.cuda(),
        max_new_tokens=1000,
        top_k=50
    )
    output_str = tokenizer.batch_decode(topk_output)  # a list containing just one str

    return output_str[0]
```

So actually, we don't need `tokenizer` and `model` in `prepare_data` function.

One important note: MMedLM2-1_8B is a foundation model that has undergone continued pretraining based on internlm2-1.8B. However, it has not been fine-tuneds. So you may finetune it first for downstream task.

**Comment by JV-X** [comment]
Should line 118 be changed from ```output_str = inference_on_one(input_str)``` to ```output_str = inference_on_one(input_str, model, tokenizer)```?

**Comment by Henrychur** [comment]
Yes, thank you for your kind remind. we have fixed the bug now

**Comment by JV-X** [comment]
thanks for your effort.
