### ISSUE TITLE
List of English Language Textbooks Missing

### ISSUE THREAD

**Issue by deskool** [MAGIC-AI4Med/MMedLM#7]
The sourcelist is missing a tab for English Booknames.

**Comment by Henrychur** [comment]
Hello! The English textbooks used in this work is the same as the ones in PMC LLAMA. You can refer to this [Excel file](https://github.com/chaoyi-wu/PMC-LLaMA/blob/main/MedicalBook.xlsx) to find the list of English textbook names.
